src/PhiTrac/UserBundle/Entity/User.php
<?php

namespace PhiTrac\UserBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * User
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="PhiTrac\UserBundle\Entity\UserRepository")
 *
 * @UniqueEntity("name")
 */
class User implements UserInterface
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="username", type="string", length=100, unique=true)
     */
    private $username;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=100)
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="firstname", type="string", length=100)
     */
    private $firstname;

    /**
     * @var string
     *
     * @ORM\Column(name="password", type="string", length=255)
     */
    private $password;

    /**
     * @var string
     *
     * @ORM\Column(name="salt", type="string", length=255)
     */
    private $salt;

    /**
     * @var array
     *
     * @ORM\Column(name="roles", type="array")
     */
    private $roles;

    /**
     * @Gedmo\Slug(fields={"username"})
     *
     * @ORM\Column(name="slug", type="string", length=255, unique=true)
     */
    private $slug;
    
    
    public function __construct()
    {
        $this->roles = array();
        $this->salt = bin2hex(hash('sha256', uniqid(mt_rand(), true), true));
    }

    public function __toString(){
        return $this->getSlug();
    }


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set username
     *
     * @param string $username
     * @return User
     */
    public function setUsername($username)
    {
        $this->username = $username;

        return $this;
    }

    /**
     * Get username
     *
     * @return string 
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return User
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set firstname
     *
     * @param string $firstname
     * @return User
     */
    public function setFirstname($firstname)
    {
        $this->firstname = $firstname;

        return $this;
    }

    /**
     * Get firstname
     *
     * @return string 
     */
    public function getFirstname()
    {
        return $this->firstname;
    }

    /**
     * Set password
     *
     * @param string $password
     * @return User
     */
    public function setPassword($password)
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Get password
     *
     * @return string 
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Set salt
     *
     * @param string $salt
     * @return User
     */
    public function setSalt($salt)
    {
        $this->salt = $salt;

        return $this;
    }

    /**
     * Get salt
     *
     * @return string 
     */
    public function getSalt()
    {
        return $this->salt;
    }

    /**
     * Set roles
     *
     * @param array $roles
     * @return User
     */
    public function setRoles(array $roles)
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * Get roles
     *
     * @return array 
     */
    public function getRoles()
    {
        return $this->roles;
    }

    public function getRole()
    {
        return $this->roles[0];
    }
    
    public function eraseCredentials()
    {
        
    }

    /**
     * Set slug
     *
     * @param string $slug
     * @return User
     */
    public function setSlug($slug)
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * Get slug
     *
     * @return string 
     */
    public function getSlug()
    {
        return $this->slug;
    }
}

src/PhiTrac/UserBundle/Controller/AdministrationController.php
<?php

namespace PhiTrac\UserBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use PhiTrac\UserBundle\Entity\User;
use PhiTrac\UserBundle\Form\Type\UserType;

class AdministrationController extends Controller
{
    public function homeAction()
    {
        $repository = $this->getDoctrine()->getManager()->getRepository('PhiTracUserBundle:User');
        $users = $repository->findAllAlphabetical();
        
        return $this->render('PhiTracUserBundle:Administration:home.html.twig', array("users" => $users));
    }
    
    public function createUserAction()
    {
        $user = new User();
		
		$form = $this->createForm(new UserType, $user);
		
        $request = $this->get('request');
        if ($request->getMethod()=='POST') {
            $form->bind($request);
            
            if ($form->isValid()) {
		        $em = $this->getDoctrine()->getManager();

		        $encoder = $this->get('security.encoder_factory')->getEncoder($user);
                $user->setPassword($encoder->encodePassword($user->getPassword(), $user->getSalt()));
                
                $user->setRoles(array($form->get('roles')->getData()));
		        
                $em->persist($user);
		        $em->flush();
		        
		        return $this->redirect($this->generateUrl('administration_home'));
	        }
        }        

        return $this->render('PhiTracUserBundle:Administration:createUser.html.twig', array('form' => $form->createView()));
    }
}

src/PhiTrac/UserBundle/Resources/views/Administration/createUser.html.twig
{% extends "::layout.html.twig" %}

{% block title %}{{ parent() }} - Create new user{% endblock %}

{% block project %}
	<h2>Create a new user</h2>
{% endblock %}

{% block guideline %}
    {{ parent() }}
    <li><a href="{{ path('administration_home') }}">Administration</a></li>
    <li class="active">Create a new user</li>
{% endblock %}

{% block body %}
<div class="well form-horizontal">
	<form method="post">
        <div class="row">
            {{ form_label(form.username, "Username:", {"label_attr": {"class": "col-xs-4 col-sm-3 col-md-3 col-lg-2"}}) }}
            {{ form_widget(form.username, {"attr": {"class": "col-xs-8 col-sm-5 col-md-3 col-lg-2"}}) }} 
            {{ form_errors(form.username) }}
        </div>
        <div class="row">
            {{ form_label(form.firstname, "Firstname:", {"label_attr": {"class": "col-xs-4 col-sm-3 col-md-3 col-lg-2"}}) }}
            {{ form_widget(form.firstname, {"attr": {"class": "col-xs-8 col-sm-5 col-md-3 col-lg-2"}}) }} 
            {{ form_errors(form.firstname) }}
        </div>
        <div class="row">
            {{ form_label(form.name, "Name:", {"label_attr": {"class": "col-xs-4 col-sm-3 col-md-3 col-lg-2"}}) }}
            {{ form_widget(form.name, {"attr": {"class": "col-xs-8 col-sm-5 col-md-3 col-lg-2"}}) }} 
            {{ form_errors(form.name) }}
        </div>
        <div class="row">
            {{ form_label(form.password, "Password:", {"label_attr": {"class": "col-xs-4 col-sm-3 col-md-3 col-lg-2"}}) }}
            {{ form_widget(form.password, {"attr": {"class": "col-xs-8 col-sm-5 col-md-3 col-lg-2"}}) }} 
            {{ form_errors(form.password) }}
        </div>
        <div class="row">
            {{ form_label(form.roles, "Category:", {"label_attr": {"class": "col-xs-4 col-sm-3 col-md-3 col-lg-2"}}) }}
            {{ form_widget(form.roles, {"attr": {"class": "col-xs-8 col-sm-5 col-md-3 col-lg-2"}}) }} 
            {{ form_errors(form.roles) }}
        </div>
        {{ form_rest(form) }}
		<input type="submit" class="btn btn-primary" value="Create" />
	</form>
</div>
{% endblock%}

src/PhiTrac/UserBundle/Resources/views/Administration/home.html.twig
{% extends "::layout.html.twig" %}

{% block title %}{{ parent() }} - Administration{% endblock %}

{% block project %}
	<h2>Administration</h2>
{% endblock %}

{% block guideline %}
    {{ parent() }}
    <li class="active">Administration</li>
{% endblock %}

{% block body %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">
                Users list
                <a href="{{ path('create_user') }}" class="btn btn-default btn-xs">Create a new user</a>
            </h3>
        </div>
        <div class="list-group">
            {% for user in users %}
                <a href="{{ path('profile_show', { 'slug': user.slug }) }}" class="list-group-item">
                    {{ user.firstname ~ " " ~ user.name }}
                    {% if user.role == "ROLE_SUPER_ADMIN" %}
                        <span class="label label-danger">Super Administrator</span>
                    {% elseif user.role == "ROLE_ADMIN" %}
                        <span class="label label-warning">Administrator</span>
                    {% elseif user.role == "ROLE_DEV" %}
                        <span class="label label-success">Developer</span>
                    {% elseif user.role == "ROLE_TESTER" %}
                        <span class="label label-info">Tester</span>
                    {% else %}
                        <span class="label label-default">User</span>
                    {% endif %}
                </a>
            {% endfor %}
        </div>
    </div>
{% endblock%}